[package]
name = "image-compression"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[profile.release]
lto = true


[dependencies]
image = "0.25.2"
js-sys = "0.3.69"
wasm-bindgen = "0.2.92"
